import Head from 'next/head'
import Footer from '@/components/Footer'
import Feedbackpage from '@/components/Feedbackpage'
import Backbtn from '@/components/Backbtn'

export default function Home() {
	return (
		<>
			<Head>
				<title>Feedback | One Stop PhD Solution | MP Research Work | Mprw.in</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Feedbackpage />
			<Footer />
			<Backbtn />
		</>
	)
}
