import Head from 'next/head'
import Hero from '@/components/Hero'
import Features from '@/components/Features'
import Products from '@/components/Products'
import Producthead from '@/components/Producthead'
import About from '@/components/About'
import Company from '@/components/Company'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Backbtn from '@/components/Backbtn'
import Navbar from '@/components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>One Stop PhD Solution | MP Research Work | Mprw.in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Features />
      <Products />
      <About />
      <Producthead />
      <Company />
      <Contact />
      <Footer />
      <Backbtn />
    </>
  )
}
